/**
 * Automation inspiration cards.
 * Each card pre-fills the create form with a prompt start and default schedule.
 * Designed for non-technical users — relatable everyday use cases.
 */

export interface InspirationCard {
  id: string;
  title: string;
  description: string;
  promptStart: string;       // Pre-filled text, user completes it
  defaultSchedule: string;   // Cron expression
  icon: string;              // Emoji
  integrationId?: string;    // If set, card only shows when this integration is connected
}

export const INSPIRATION_CARDS: InspirationCard[] = [
  {
    id: 'price-alert',
    title: 'Price Alert',
    description: 'Get notified when a crypto or stock hits your target',
    promptStart: 'Watch the price of Bitcoin and alert me when it ',
    defaultSchedule: '*/15 * * * *',
    icon: '\u{1F4C8}',
  },
  {
    id: 'daily-digest',
    title: 'Daily Digest',
    description: 'A summary of the most important things each morning',
    promptStart: 'Summarize the most important things I should know today, including ',
    defaultSchedule: '0 8 * * *',
    icon: '\u{1F4CB}',
  },
  {
    id: 'email-summary',
    title: 'Email Summary',
    description: 'Highlights from your inbox so you never miss what matters',
    promptStart: 'Check my recent emails and highlight anything urgent or important, especially ',
    defaultSchedule: '0 9 * * *',
    icon: '\u{1F4E7}',
  },
  {
    id: 'email-urgent-alert',
    title: 'Urgent Email Alert',
    description: 'Get notified when you receive emails that need immediate attention',
    promptStart: 'Check my inbox for any urgent or time-sensitive emails from ',
    defaultSchedule: '*/30 * * * *',
    icon: '\u{1F6A8}',
  },
  {
    id: 'email-daily-digest',
    title: 'Inbox Digest',
    description: 'A clean summary of your inbox every morning',
    promptStart: 'Summarize my unread emails from the last 24 hours, grouped by priority. Focus on ',
    defaultSchedule: '0 8 * * *',
    icon: '\u{1F4EC}',
  },
  {
    id: 'email-auto-draft',
    title: 'Draft Replies',
    description: 'Let AI prepare reply drafts for emails that need a response',
    promptStart: 'Check my unread emails and draft replies for any that need a response, especially ',
    defaultSchedule: '0 9 * * *',
    icon: '\u{270D}\u{FE0F}',
  },
  // ── Business integration cards (gated by integrationId) ──────────────────
  {
    id: 'stripe-revenue',
    title: 'Revenue Report',
    description: 'Track your Stripe revenue and subscription metrics',
    promptStart: 'Show my Stripe revenue summary including active subscriptions, recent invoices, and ',
    defaultSchedule: '0 9 * * 1',
    icon: '\u{1F4B3}',
    integrationId: 'stripe_integration',
  },
  {
    id: 'github-pr-review',
    title: 'PR Review',
    description: 'Stay on top of open pull requests on GitHub',
    promptStart: 'List my open pull requests on GitHub and highlight any that need my review, especially ',
    defaultSchedule: '0 9 * * 1-5',
    icon: '\u{1F419}',
    integrationId: 'github',
  },
  {
    id: 'github-issue-digest',
    title: 'Issue Digest',
    description: 'A summary of GitHub issues assigned to you',
    promptStart: 'Show GitHub issues assigned to me and summarize what needs attention, focusing on ',
    defaultSchedule: '0 9 * * 1',
    icon: '\u{1F41B}',
    integrationId: 'github',
  },
  {
    id: 'linear-standup',
    title: 'Linear Standup',
    description: 'A quick summary of your Linear issues for standup',
    promptStart: 'Summarize my assigned Linear issues — what I completed recently and what\'s in progress, especially ',
    defaultSchedule: '0 9 * * 1-5',
    icon: '\u{1F4CA}',
    integrationId: 'linear',
  },
  {
    id: 'jira-sprint',
    title: 'Sprint Status',
    description: 'Check on your Jira sprint progress',
    promptStart: 'Show the current Jira sprint status — tickets in progress, blocked, and completed. Focus on ',
    defaultSchedule: '0 9 * * 1-5',
    icon: '\u{1F3AF}',
    integrationId: 'jira',
  },
  {
    id: 'sentry-errors',
    title: 'Error Watch',
    description: 'Get alerted about new unresolved errors in Sentry',
    promptStart: 'Check Sentry for any new unresolved errors or issues that spiked recently, especially in ',
    defaultSchedule: '0 9 * * *',
    icon: '\u{1F525}',
    integrationId: 'sentry',
  },
  {
    id: 'notion-updates',
    title: 'Notion Updates',
    description: 'See what changed in your Notion workspace',
    promptStart: 'Show recently updated pages in my Notion workspace and summarize key changes, especially ',
    defaultSchedule: '0 9 * * 1',
    icon: '\u{1F4DD}',
    integrationId: 'notion',
  },
  {
    id: 'hubspot-pipeline',
    title: 'Deal Pipeline',
    description: 'Track your HubSpot deals and pipeline health',
    promptStart: 'Show my open HubSpot deals and highlight any that need follow-up or are at risk, especially ',
    defaultSchedule: '0 9 * * 1',
    icon: '\u{1F4BC}',
    integrationId: 'hubspot',
  },
  {
    id: 'datadog-alerts',
    title: 'Monitor Check',
    description: 'Get a status check on your Datadog monitors',
    promptStart: 'Check my Datadog monitors and report any that are alerting or warning, especially ',
    defaultSchedule: '0 9 * * *',
    icon: '\u{1F4DF}',
    integrationId: 'datadog',
  },
  {
    id: 'asana-tasks',
    title: 'Task Review',
    description: 'Stay on top of your Asana tasks',
    promptStart: 'Show my Asana tasks due this week and highlight anything overdue, especially ',
    defaultSchedule: '0 9 * * 1',
    icon: '\u{2705}',
    integrationId: 'asana',
  },
  {
    id: 'trello-board',
    title: 'Board Update',
    description: 'A summary of your Trello board activity',
    promptStart: 'Show Trello cards assigned to me and any recent board activity, focusing on ',
    defaultSchedule: '0 9 * * 1',
    icon: '\u{1F4CC}',
    integrationId: 'trello',
  },
  {
    id: 'calendly-upcoming',
    title: 'Upcoming Meetings',
    description: 'See your Calendly schedule for the day',
    promptStart: 'Show my upcoming Calendly events for today and tomorrow, including ',
    defaultSchedule: '0 8 * * 1-5',
    icon: '\u{1F4C6}',
    integrationId: 'calendly',
  },
  {
    id: 'zendesk-tickets',
    title: 'Ticket Queue',
    description: 'Check on open support tickets in Zendesk',
    promptStart: 'Show my open Zendesk tickets sorted by priority and highlight any that are overdue, especially ',
    defaultSchedule: '0 9 * * 1-5',
    icon: '\u{1F3AB}',
    integrationId: 'zendesk',
  },
  {
    id: 'reminder',
    title: 'Reminder',
    description: 'Set up a recurring reminder for anything',
    promptStart: 'Remind me to ',
    defaultSchedule: '0 9 * * *',
    icon: '\u{1F514}',
  },
  {
    id: 'news-brief',
    title: 'News Brief',
    description: 'Stay on top of topics you care about',
    promptStart: 'Give me a quick summary of today\'s top news about ',
    defaultSchedule: '0 8 * * *',
    icon: '\u{1F4F0}',
  },
  {
    id: 'health-checkin',
    title: 'Health Check-In',
    description: 'A gentle daily check-in to track how you\'re doing',
    promptStart: 'Ask me how I\'m feeling today and suggest ',
    defaultSchedule: '0 18 * * *',
    icon: '\u{1F49A}',
  },
  {
    id: 'weekly-review',
    title: 'Weekly Review',
    description: 'Look back at the week and plan ahead',
    promptStart: 'Summarize what happened this week and suggest priorities for next week, focusing on ',
    defaultSchedule: '0 9 * * 1',
    icon: '\u{1F4C5}',
  },
];
